[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://server-frontend-backend-generator.onrender.com"

# API proxy
[[redirects]]
  from = "/api/*"
  to = "https://server-frontend-backend-generator.onrender.com/api/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200